var data = {
    saveBo:{
        userId:"zhangsan",
        tenantId:'j0h7ehoz',
        "bo":{
            "bo_code":"SFExpress",
                "bo_name":"顺丰快递",
                "tenant_id":"j0h7ehoz",
                "app_id":"1",
                "bo_attrs":[
                {
                    "name":"寄件单位名称",
                    "code":"fromComp",
                    "typename":"fromComp",
                    "fieldtype":"VARCHAR",
                    "fieldname":"fromComp",
                    "isPrimary":"0"
                },
                {
                    "name":"寄件人",
                    "code":"fromUser",
                    "typename":"fromUser",
                    "fieldtype":"VARCHAR",
                    "fieldname":"fromUser",
                    "isPrimary":"0"
                },
                {
                    "name":"寄件地址",
                    "code":"fromAddr",
                    "typename":"fromAddr",
                    "fieldtype":"VARCHAR",
                    "fieldname":"fromAddr",
                    "isPrimary":"0"
                },
                {
                    "name":"寄件人联系电话",
                    "code":"fromTelphone",
                    "typename":"fromTelphone",
                    "fieldtype":"VARCHAR",
                    "fieldname":"fromTelphone",
                    "isPrimary":"0"
                },
                {
                    "name":"寄件单位名称",
                    "code":"arriveComp",
                    "typename":"arriveComp",
                    "fieldtype":"VARCHAR",
                    "fieldname":"arriveComp",
                    "isPrimary":"0"
                },
                {
                    "name":"收件人",
                    "code":"recipient",
                    "typename":"recipient",
                    "fieldtype":"VARCHAR",
                    "fieldname":"recipient",
                    "isPrimary":"0"
                },
                {
                    "name":"收件地址",
                    "code":"recipientAttr",
                    "typename":"recipientAttr",
                    "fieldtype":"VARCHAR",
                    "fieldname":"recipientAttr",
                    "isPrimary":"0"
                },
                {
                    "name":"收件联系电话",
                    "code":"recipientTelphone",
                    "typename":"recipientTelphone",
                    "fieldtype":"VARCHAR",
                    "fieldname":"recipientTelphone",
                    "isPrimary":"0"
                },
                {
                    "name":"托件物详细资料",
                    "code":"detailCare",
                    "typename":"detailCare",
                    "fieldtype":"VARCHAR",
                    "fieldname":"detailCare",
                    "isPrimary":"0"
                },
                {
                    "name":"收件员",
                    "code":"receiver",
                    "typename":"receiver",
                    "fieldtype":"VARCHAR",
                    "fieldname":"receiver",
                    "isPrimary":"0"
                },
                {
                    "name":"派件员",
                    "code":"sender",
                    "typename":"sender",
                    "fieldtype":"VARCHAR",
                    "fieldname":"sender",
                    "isPrimary":"0"
                },
                {
                    "name":"原寄地编码",
                    "code":"fromAttrCode",
                    "typename":"fromAttrCode",
                    "fieldtype":"VARCHAR",
                    "fieldname":"fromAttrCode",
                    "isPrimary":"0"
                },
                {
                    "name":"目的地编码",
                    "code":"destinationCode",
                    "typename":"destinationCode",
                    "fieldtype":"VARCHAR",
                    "fieldname":"destinationCode",
                    "isPrimary":"0"
                },
                {
                    "name":"费用 Charge",
                    "code":"charge",
                    "typename":"charge",
                    "fieldtype":"VARCHAR",
                    "fieldname":"charge",
                    "isPrimary":"0"
                },
                {
                    "name":"件数",
                    "code":"count",
                    "typename":"count",
                    "fieldtype":"VARCHAR",
                    "fieldname":"count",
                    "isPrimary":"0"
                },
                {
                    "name":"实际重量(公斤)",
                    "code":"realWeight",
                    "typename":"realWeight",
                    "fieldtype":"VARCHAR",
                    "fieldname":"realWeight",
                    "isPrimary":"0"
                },
                {
                    "name":"运费",
                    "code":"freight",
                    "typename":"freight",
                    "fieldtype":"VARCHAR",
                    "fieldname":"freight",
                    "isPrimary":"0"
                },
                {
                    "name":"付款方式 Payment",
                    "code":"payment",
                    "typename":"payment",
                    "fieldtype":"VARCHAR",
                    "fieldname":"payment",
                    "isPrimary":"0"
                }
            ]
        }
    },
    design:{
        tenantId:'j0h7ehoz',
        bocode:'SFExpress1',
        reportName:'测试名字',
        type:'48a8206f-6759-431e-bf84-e973935e2fcc'
},
    view:{

    }
}
module.exports = data;